### PR TITLE
feat: created footer containing social media details

### LINKED ISSUE #43: Add social media links to home page
Currently the links to GitHub, Instagram and Facebook  profiles are available in the /about-us page but most users don't go to that page at all so... I think it will be nice to have a fixed footer with all those links to quick access them from home page.

Here's a reference (just the icons part): 
[https://bbbootstrap.com/snippets/bootstrap-dark-website-footer-social-media-icons-46403047](url)

Please keep in mind that users access this site mainly from mobile phones.

### PR DESCRIPTION
**Pull request by supminn**
I have created a footer component that contains the details present on the about-us page.

Screenshot:
image

### CODE REVIEW

**Comment by amaliaibarra** [comment]
Hi @supminn! Sorry for the late response. Great job! The footer looks great!! But I'm afraid It's more than we expected, this is totally my fault, I should have been more specific in the description.  

I'll try to explain it more carefully:
- The footer should only contain the links to Instagram, Facebook and GitHub. No other information needed.
- It should be fixed in home page, like the Add button.
- With background color: rgb(255,250,238)
- icons color: #e27e22 and use their rounded version (BsFacebook, BsGitHub, BsInstagram)
- The priority is that the footer looks good on mobile phones. Please send a screenshot showing what it would look like.

I'm sorry for the trouble, thank you very much for your hard work!!

**Review by josejorgers — COMMENTED** [review]
@supmin I think you did it great! @amaliaibarra maybe we can think of that current version as the one for desktop view.

Also, I want to highlight that the implementation is great and it would be approved if we were not that bad at writing issues. We are total noobs on it!

Thanks, @supmin!

**Comment by amaliaibarra** [comment]
Great job @supminn!! The footer looks amazing. You are our first foreign contributor!! Hooray!! Thank you very much for your collaboration. We really apprecciate it. Keep up the good work :)  Happy hacktoberfest!

**Comment by supminn** [comment]
Thank you @amaliaibarra!
I just started out with open source contribution with hacktoberfest 2021. It's really nice to collaborate for a budding project. I look forward to contribute more.

I see that this project is not participating in hacktoberfest-2021, is this for a specific reason?
image

**Comment by amaliaibarra** [comment]
Sorry @supmin , we forgot to add the 'hacktoberfest' topic to our repository. I already added it and also the hacktoberfest-accepted label to the PR. Let me know if anything changes. Sorry again.

**Review by amaliaibarra — COMMENTED** [review]
Great job. Changes are ready to merge.

**Pull request merged**
